#!/usr/bin/env python3
"""Extract DPO training pairs from model-annotated fish completion files.

Reads annotated files from a directory, classifies model output as
valid/partial/broken, and for failures generates correct annotations
to create (prompt, chosen, rejected) DPO pairs.

The "chosen" annotations are generated by this script reading the fish
file and producing a correct annotation. For production use, these
should be reviewed by a human or validated by a stronger model.

Usage:
    python3 training/extract_dpo_pairs.py /tmp/dpo-batch
"""

import json
import re
import sys
from pathlib import Path

OUTPUT = Path("training/annotation_dpo_pairs.jsonl")

INSTRUCTION = "Generate a mogfish annotation for this command documentation"


def parse_annotated_file(path: Path) -> tuple[str, str, str]:
    """Parse an annotated fish file into (command, original_content, model_output).

    Returns (command_name, original_fish_content, raw_annotation_json_or_empty).
    """
    content = path.read_text()
    command = path.stem

    # Extract annotation block
    description = ""
    intents = []
    flags_text = []

    lines = content.split("\n")
    original_start = 0

    for i, line in enumerate(lines):
        if line.startswith("# mog-description: "):
            description = line[len("# mog-description: "):]
        elif line.startswith("# mog-intent: "):
            intents.append(line[len("# mog-intent: "):])
        elif line.startswith("# mog-flags: "):
            flags_text.append(line[len("# mog-flags: "):])
        elif line.strip() == "# --- end mog annotations ---":
            original_start = i + 1
            break

    # Reconstruct original content (after end marker)
    original = "\n".join(lines[original_start:])

    # Build model output as JSON
    if description:
        flags = []
        for ft in flags_text:
            # Parse "flag — description" format
            if " — " in ft:
                f, d = ft.split(" — ", 1)
                flags.append({"flag": f.strip(), "description": d.strip()})
            elif " - " in ft:
                f, d = ft.split(" - ", 1)
                flags.append({"flag": f.strip(), "description": d.strip()})

        model_output = json.dumps({
            "description": description,
            "intents": intents,
            "flags": flags,
        })
    else:
        model_output = ""

    return command, original, model_output


def classify_output(model_output: str, original_content: str) -> str:
    """Classify model output as valid, partial, or broken."""
    if not model_output:
        return "broken"

    try:
        ann = json.loads(model_output)
    except json.JSONDecodeError:
        return "broken"

    desc = ann.get("description", "")
    intents = ann.get("intents", [])
    flags = ann.get("flags", [])

    if not desc or not intents:
        return "broken"

    # Check for repetition in intents
    if len(intents) > 3 and len(set(intents)) < len(intents) / 2:
        return "partial"

    # Check if flags should be present but aren't
    has_flag_defs = bool(re.search(r"complete\s.*-[sl]\s", original_content))
    if has_flag_defs and not flags:
        return "partial"

    # Check for degenerate content (>50% single token)
    all_text = desc + " ".join(intents)
    tokens = all_text.split()
    if tokens:
        from collections import Counter
        most_common = Counter(tokens).most_common(1)[0][1]
        if most_common > len(tokens) * 0.5:
            return "partial"

    return "valid"


def generate_correct_annotation(command: str, original_content: str) -> str:
    """Generate a correct annotation from the fish completion file.

    This is a rule-based extraction — reads complete -c lines to find
    flags and descriptions. Not as good as an LLM annotation but
    provides structurally correct ground truth for DPO.
    """
    flags = []
    descriptions = set()

    for line in original_content.split("\n"):
        line = line.strip()
        if not line.startswith("complete") or f"-c {command}" not in line and f"-c '{command}'" not in line and f'-c "{command}"' not in line:
            # Try without quotes
            if not (line.startswith("complete") and command in line):
                continue

        # Extract short flag
        short = ""
        long_flag = ""
        desc = ""

        short_match = re.search(r"-s\s+(\S+)", line)
        if short_match:
            short = f"-{short_match.group(1)}"

        long_match = re.search(r"-l\s+(\S+)", line)
        if long_match:
            long_flag = f"--{long_match.group(1)}"

        desc_match = re.search(r"-d\s+['\"]([^'\"]+)['\"]", line)
        if not desc_match:
            desc_match = re.search(r"-d\s+(\S+)", line)
        if desc_match:
            desc = desc_match.group(1)

        if (short or long_flag) and desc:
            flag_name = f"{short}/{long_flag}" if short and long_flag else (short or long_flag)
            if flag_name not in [f["flag"] for f in flags]:
                flags.append({"flag": flag_name, "description": desc})

        # Collect descriptions for intents
        if desc and len(desc) > 5:
            descriptions.add(desc)

    # Build annotation
    intents = [f"use {command}"]
    for d in list(descriptions)[:4]:
        intents.append(d.lower() if len(d) < 50 else d[:50].lower())

    if len(intents) < 3:
        intents.extend([f"run {command}", f"{command} command"])
    intents = intents[:5]

    return json.dumps({
        "description": f"Command-line tool for {command}",
        "intents": intents,
        "flags": flags[:10],
    })


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <annotated-dir>", file=sys.stderr)
        sys.exit(1)

    batch_dir = Path(sys.argv[1])
    if not batch_dir.exists():
        print(f"Directory not found: {batch_dir}", file=sys.stderr)
        sys.exit(1)

    valid = 0
    partial = 0
    broken = 0
    pairs = []

    for fish_file in sorted(batch_dir.glob("*.fish")):
        command, original, model_output = parse_annotated_file(fish_file)
        classification = classify_output(model_output, original)

        if classification == "valid":
            valid += 1
        elif classification in ("partial", "broken"):
            if classification == "partial":
                partial += 1
            else:
                broken += 1

            # Generate correct annotation
            correct = generate_correct_annotation(command, original)

            prompt = f"{INSTRUCTION}\n\nCommand: {command}\n\n{original[:2000]}"

            pair = {
                "prompt": prompt,
                "chosen": correct,
                "rejected": model_output if model_output else "{}",
            }
            pairs.append(pair)

    print(f"Results: {valid} valid, {partial} partial, {broken} broken")
    print(f"DPO pairs generated: {len(pairs)}")

    # Write pairs
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT, "w") as f:
        for pair in pairs:
            f.write(json.dumps(pair) + "\n")

    print(f"Written to {OUTPUT}")


if __name__ == "__main__":
    main()
